polls/urls.py
from django.urls import path
from . import views


app_name = 'polls'
urlpatterns = [
    # ex /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex /polls/5/vote/
    path('<str:question_id>/vote/', views.vote, name='vote'),
    # Let's say you wanted to let users put stuff in your DB
    # like /polls/sql/?str
    path('sql/', views.sql_injector, name='sqlinject'),
    # ex /polls/search/
    path('search/', views.search, name='search'),
    # ex /polls/injector/
    path('<str:injector_str>/', views.inject, name='inject'),

]

vuln_django/urls.py
from django.contrib import admin
from django.urls import include, path
from vuln_django import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.redirect_to_polls, name="index"),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    questions_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.questions_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.db import connection
from urllib.parse import unquote
from django.views.decorators.csrf import csrf_exempt
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Exclude any questions that aren't published yet
        :return:
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Exclude any questions that aren't published yet
        :return:
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


@csrf_exempt
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = { 'latest_question_list': latest_question_list, }
    return render(request, 'polls/index.html', context)


@csrf_exempt
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


@csrf_exempt
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


@csrf_exempt
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # redisplay the question voting form
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents the data from being posted twice if a
        # user hist the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


@csrf_exempt
def inject(request, injector_str):
    response = "You're looking at the page that handles injection of %s"
    return render(request, 'polls/injector.html', {
        'injector_str': unquote(injector_str),
    })


@csrf_exempt
def sql_injector(request, ):
    sql_str = request.GET.get('sql')
    prepared_sql = request.GET['sql']
    cursor = connection.cursor()
    cursor.execute(prepared_sql)
    sql_results = cursor.fetchall()
    cursor.close()
    return render(request, 'polls/sequeleye.html', {
        'sql_str': sql_str,
        'sql_results': sql_results,
    }) #HttpResponse("Ohh, my DB info, yeah it's here: " + str(sql_results))


@csrf_exempt
def search(request, ):
    search_str = request.POST.get('search_string', 'found nothing in search')
    return render(request, 'polls/search_detail.html', {'search_string': search_str,})

vuln_django/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.db import connection
from urllib.parse import unquote
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def redirect_to_polls(request, ):
    return HttpResponseRedirect('/polls')

polls/templates/polls/detail.html
{% extends "public/base.html" %}
{% block title %}{{ question.questions_text }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{{ question.questions_text }}</h1></div>
</div>
<div class="row">
  <div class="col">
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">

    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
      <input type="submit" value="Vote">
    </form>
  </div>
</div>
{% endblock %}

polls/templates/polls/index.html
{% extends "public/base.html" %}

{% block title %}{{ category_name }}{% endblock %}

{% block content %}
{% autoescape off %}


<div class="row">
  <div class="col">
{% if latest_question_list %}
    <h2>The Latest Questions</h2>
      <ul>
      {% for question in latest_question_list %}
          <li><a href="{% url 'polls:detail' question.id %}">{{ question.questions_text }}</a></li>
      {% endfor %}
      </ul>
  {% else %}
      <p>No polls are available.</p>
  {% endif %}

  </div>
</div>
{% endautoescape %}
<div class="row">
  <div class="col">
  <p>Also, if you'd like to pwnt me, check out these links?<br>
  <a href="{% url 'polls:inject' 'rando_stuff' %}">The Injector Page</a></p>

  <p>Want to run some DB queries?<br>
  <a href="{% url 'polls:sqlinject' %}?sql=SELECT name FROM sqlite_master WHERE type='table'">The SQL Injector Page</a></p>
</div>

  <div class="col">
    <p>also if you'd like to search for some stuff do it here</p>
    <form action="{% url 'polls:search' %}" method="post">
      <input type="text" name="search_string" id="search_string" value="">
      <input type="submit" value="Search">
    </form>
  </div>
</div>
{% endblock %}

polls/templates/polls/injector.html
{% extends "public/base.html" %}
{% block title %}{{ "Ohh hey!" }}{% endblock %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col"><h1>This page displays stuff from the url</h1></div>
</div>
<div class="row">
  <div class="col"<li>You sent me {{ injector_str }}.</li></div>
</div>
<div class="row">
  <div class="col">
    {% autoescape off %}

    I gave you back {{ injector_str }}. Happy birthday.

    {% endautoescape %}
  </div>
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends "public/base.html" %}
{% block title %}{{ question.questions_text }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{{ question.questions_text }}</h1></div>
</div>
<div class="row">
  <div class="col">
  <ul>
      {% for choice in question.choice_set.all %}
          <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
      {% endfor %}
  </ul>

  <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
  </div>
</div>
{% endblock %}

polls/templates/polls/search_detail.html
{% extends "public/base.html" %}
{% block title %}{{ question.questions_text }}{% endblock %}

{% block content %}
<div class="row">
  <div class="col">
    <h1>You searched for:</h1>
 </div>
</div>
<div class="row">
  <div class="col">
    <p>{{ search_string }}</p>

    <p>and we found exactly that:</p>

    {% autoescape off %}
    {{ search_string }}
    {% endautoescape %}
  </div>
</div>
{% endblock %}

polls/templates/polls/sequeleye.html
{% extends "public/base.html" %}
{% block title %}{{ "Ohh hey!" }}{% endblock %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col"><h1>This page allows you to make DB queries</h1></div>
</div>
<div class="row">
  <div class="col"<li>You sent me '{{ sql_str }}'.</li></div>
</div>
<div class="row">
  <div class="col">
    {% autoescape off %}

    I gave you back {{ sql_results }}.

    {% endautoescape %}
  </div>
</div>
<div class="row mt-4">
  <div class="col">
    Try Again?:
    <form class="form" method="get" action="/polls/sql/">
      <div class="form-group">
        <label for="sql">DB Query</label>
        <input type="string" class="form-control" id="sql" name="sql" aria-describedby="SQLi">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
</div>
{% endblock %}